version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "83:80"
    volumes:
      - ./UI:/usr/share/nginx/html
    restart: always
  api:
    build: ./API
    ports:
      - "8083:8083"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=blog
    depends_on:
      - db
    restart: always
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: blog
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"